spring:
#application name
  application:
    name: et-user-auth-service

#mongo-db
  data:
   mongodb:
     uri: mongodb://localhost:27107/
     database: et-user-auth-service

#port no
   server:
     port: 8081
